name: Maven java 10 Build

on:
  push:
    branches:
      - java10
jobs:
  build:

    runs-on: docker://maven:3.6.0-jdk-10

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven clean
      run: mvn clean --file pom.xml
    - name: Maven compile
      run: mvn compile --file pom.xml
    - name: Maven test
      run: mvn test --file pom.xml
    - name: Maven install
      run: mvn install -Dmaven.test.skip=true --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: PluginJars
        path: staging